format = '''
[┌](bold green) $os $shell$status $deno$docker_context$elixir$elm$fennel$fossil_branch$gcloud$golang$gradle$guix_shell$haskell$haxe$hg_branch$hostname$java$julia$kotlin$lua$memory_usage$meson$nim$nix_shell$nodejs$ocaml$package$perl$php$pijul_channel$pixi$python$rlang$ruby$rust$scala$swift$zig
[│](bold green)$directory$git_branch$git_status$git_commit
[└](bold green)'''

scan_timeout = 20

add_newline = false 

[shell]
zsh_indicator = ' '
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[directory]
home_symbol = ''

[os]
format = "[$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Arch = " "

[status]
symbol = ' error'
failure_style = 'red bold'
success_symbol = ' '
not_executable_symbol = ' '
not_found_symbol = ' '
signal_symbol = '󱐌 '
success_style = 'green bold'
format = '[$symbol]($style)'
map_symbol = true
disabled = false

[git_branch]
symbol = " "
truncation_symbol = ''

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '[$conflicted$deleted$modified$typechanged$staged$untracked$ahead_behind]($style)'

[deno]
symbol = " "
format = '[$symbol($version )]($style)' 

[docker_context]
symbol = " "
format = '[$symbol($version )]($style)' 

[elixir]
symbol = " "
format = '[$symbol($version )]($style)' 

[elm]
symbol = " "
format = '[$symbol($version )]($style)' 

[fennel]
symbol = " "
format = '[$symbol($version )]($style)' 

[gcloud]
symbol = " "
format = '[$symbol($version )]($style)' 

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "
format = '[$symbol($version )]($style)' 

[gradle]
symbol = " "
format = '[$symbol($version )]($style)' 

[guix_shell]
symbol = " "
format = '[$symbol($version )]($style)' 

[haskell]
symbol = " "
format = '[$symbol($version )]($style)' 

[haxe]
symbol = " "
format = '[$symbol($version )]($style)' 

[hg_branch]
symbol = " "
format = '[$symbol($version )]($style)' 

[java]
symbol = " "
format = '[$symbol($version )]($style)' 

[julia]
symbol = " "
format = '[$symbol($version )]($style)' 

[kotlin]
symbol = " "
format = '[$symbol($version )]($style)' 

[lua]
symbol = " "
format = '[$symbol($version )]($style)' 

[memory_usage]
symbol = "󰍛 "
format = '[$symbol($version )]($style)' 

[meson]
symbol = "󰔷 "
format = '[$symbol($version )]($style)' 

[nim]
symbol = "󰆥 "
format = '[$symbol($version )]($style)' 

[nix_shell]
symbol = " "
format = '[$symbol($version )]($style)' 

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)' 

[ocaml]
symbol = " "
format = '[$symbol($version )]($style)' 

[package]
symbol = "󰏗 "
format = '[$symbol($version )]($style)' 

[perl]
symbol = " "
format = '[$symbol($version )]($style)' 

[php]
symbol = " "
format = '[$symbol($version )]($style)' 

[pijul_channel]
symbol = " "
format = '[$symbol($version )]($style)' 

[pixi]
symbol = "󰏗 "
format = '[$symbol($version )]($style)' 

[python]
symbol = " "
format = '[$symbol($version )]($style)' 

[rlang]
symbol = "󰟔 "
format = '[$symbol($version )]($style)' 

[ruby]
symbol = " "
format = '[$symbol($version )]($style)' 

[rust]
symbol = "󱘗 "
format = '[$symbol($version )]($style)' 

[scala]
symbol = " "
format = '[$symbol($version )]($style)' 

[swift]
symbol = " "
format = '[$symbol($version )]($style)' 

[zig]
symbol = " "
format = '[$symbol($version )]($style)' 
